dataset: online

data:
  datadir: /online/
  start: 0 
  output_dir: ./results
  gap: 25


cam:
  H: 480
  W: 640
  fx: 320.0
  fy: 320.0
  cx: 319.5
  cy: 239.5
  png_depth_scale: 1000.

detection:
  score_thresh: 0.35 #0.4 #0.25
  uv_bound: True
  uv_bound_value: 0.9
  floor_mask: True #False
  floor_ratio: 15

association:
  small_threshold: 0.1 #0.2
  rotation_gap: 30 #30
  translation_gap: 0.8 #1.0 #0.8 #0.5 #0.5 best #1.0 #0.1


box_fusion:
  use: True 
  iters: 20 
  pst_path: ./data/pst_1024_0.tiff
  pst_size: 1024
  random_opt:
    center_init_size: 0.1 
    center_scaling_coefficient:  0.1
    shape_init_size: 0.5
    shape_scaling_coefficient: 0.5 
  check_valid: False
  nms_threshold: 0.1 
  small_size: 0.35


vis:
  rerun: True 
  show_class: False 
  show_label: False 
  trajectory: True

eval: False